core_homepage:
    path:    /
    defaults:
        _controller: CoreBundle:Core:index
core_platform_accueil:
    path:    /platform/{page}
    defaults:
        _controller: OCPlatformBundle:Advert:index
        page:    1
core_contact:
    path: /contact
    defaults:
        _controller: CoreBundle:Core:contact