#oc_platform_homepage:
#    path:     /
#    defaults: { _controller: OCPlatformBundle:Default:index }
hello_the_world:
    path:     /hello-world
    defaults: {_controller: OCPlatformBundle:Advert:index }
byebye_the_world:
    path:     /byebye-world
    defaults: {_controller: OCPlatformBundle:AdvertTest:index }
rebonjour_le_monde:
    path:     /bonjour-monde
    defaults: {_controller: OCPlatformBundle:Advert:bonjour }