services:
#   oc_platform.example:
#       class: OC\PlatformBundle\Example
#       arguments: ["@service_id", "plain_value", "%parameter%"]
    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments:
            - "@mailer"
            - 50
        calls:
            - [ setLocale, [%locale%] ]

    oc_platform.twig.antispam_extension:
        class: OC\PlatformBundle\Twig\AntispamExtension
        arguments:
            - "@oc_platform.antispam"
        tags:
            - { name: twig.extension }

    oc_platform.email.application_mailer:
        class: OC\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    oc_platform.doctrine_listener.application_creation:
        class: OC\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@oc_platform.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    oc_platform.purger.purgerAdvert:
        class: OC\PlatformBundle\Purger\PurgerAdvert
        arguments:
            - "@doctrine.orm.entity_manager"
        requirements:
            days: \d+

    oc_platform.validator.antiflood:                                                                                              # Le nom du service
        class: OC\PlatformBundle\Validator\AntifloodValidator                                                                     # La classe du service, ici notre validateur déjà crée
        arguments: ["@request_stack", "@doctrine.orm.entity_manager", "@oc_platform.antiflood.antiflood_message"]                 # Les données qu'on injecte au service, ici la requête et l'EntityManager
        tags:
            - { name: validator.constraint_validator, alias: oc_platform_antiflood }                                              # C'est avec l'alias qu'on retrouvera le service

    oc_platform.antiflood.antiflood_message:
        class: OC\PlatformBundle\Antiflood\AntifloodMessage
        arguments:
            - "@doctrine.orm.entity_manager"